### ISSUE TITLE
Bindaas seemingly runs fine. But the browser doesn't show the admin console

### ISSUE THREAD

**Issue by Raj2367** [sharmalab/bindaas#98] opened 2020-01-15 10:02 UTC
# error 
after following all instruction in readme, when I am trying to open  http://localhost:8080/dashboard/ it is showing error as folowing
![error](https://user-images.githubusercontent.com/41533712/72424398-efc7b780-37ab-11ea-8b22-55e7d1fdde3a.png)
# expected behaviour
it should show the login page 
# outcome
it is showing http error 404

OS : ubuntu
browser : chrome

**Comment by Raj2367** [comment] 2020-01-15 10:04
@pradeeban What can I do for this?

**Comment by pradeeban** [comment] 2020-01-15 12:59
1. Did you run a released binary? If so, which version? 
2. Or did you build it from the source? If so, which branch?
3. I assume you run using "sh startup.sh"

Instead of #3, what is the output when your run the below?

java -Dpid=BINDAAS_INSTANCE -Xmx1024m -jar org.eclipse.osgi_3.10.100.v20150529-1857.jar -console"

and go again to http://localhost:8080/dashboard/ in the browser to see anything printed on the console.

Type "ss" on the output osgi console. What is the output?

**Comment by Raj2367** [comment] 2020-01-15 15:50
1. No,I didn't build the realeased binary.
2. I build it from the source in the master branch.
3. Yes, I am runing "sh startup.sh". 

The output for "ss" on the output osgi console is

![error2](https://user-images.githubusercontent.com/41533712/72448299-c5dab900-37dc-11ea-9815-0c1c83305124.png)
![error3](https://user-images.githubusercontent.com/41533712/72448310-cbd09a00-37dc-11ea-8ab2-d46990c90dcc.png)

**Comment by pradeeban** [comment] 2020-01-15 16:45
Nothing strange spotted in your output. 

Go to localhost:8080 in browser and see what is showing.

You must be using port 8080 for something else such as a wildfly application server. Find and kill that process first before running Bindaas.

sudo lsof -i tcp:8080

Make sure port 8080 and 9099 are free for Bindaas before running Bindaas. 

Then you should be able to go to Bindaas using the same steps.

**Comment by Raj2367** [comment] 2020-01-15 19:53
There is no process running on the port 8080 but still that error is there

![Screenshot from 2020-01-16 01-15-24](https://user-images.githubusercontent.com/41533712/72465864-f1ba6680-37fd-11ea-8b4c-30f933e6654f.png)


And there is no process for port 9099 also

![Screenshot from 2020-01-16 01-19-16](https://user-images.githubusercontent.com/41533712/72466138-4fe74980-37fe-11ea-970b-74ffa1f33062.png)

**Comment by pradeeban** [comment] 2020-01-15 23:39
Just to be sure I am not missing anything, I rebuilt the master. I couldn't reproduce your issue.

What is your java version?

This is what I have:
$ java -version
java version "1.8.0_172"
Java(TM) SE Runtime Environment (build 1.8.0_172-b11)
Java HotSpot(TM) 64-Bit Server VM (build 25.172-b11, mixed mode)


Did you see all the below logs when you run Bindaas?
____________________________
Welcome to Apache Felix Gogo
g! 15 Jan 2020 18:35:49,909 DEBUG bundle.Activator - Starting Bundle [bindaas-core-api]
15 Jan 2020 18:36:01,059 WARN  server.RealmVerifier - RP discovery / realm validation disabled; 
SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
15 Jan 2020 18:36:02,369 DEBUG util.DynamicProperties - Loaded default properties. mailService.properties (No such file or directory)
15 Jan 2020 18:36:02,535 DEBUG util.DynamicProperties - Loaded default properties. bindaas.authentication.ldap.properties (No such file or directory)
15 Jan 2020 18:36:02,795 DEBUG hibernateh2.HibernateEntityScanner - Discovered Hibernate-Entity class [edu.emory.cci.bindaas.security.model.hibernate.AuditMessage] in bundle [bindaas-security-api]
15 Jan 2020 18:36:02,796 DEBUG hibernateh2.HibernateEntityScanner - Discovered Hibernate-Entity class [edu.emory.cci.bindaas.security_dashboard.model.hibernate.Policy] in bundle [security-dashboard]
15 Jan 2020 18:36:02,796 DEBUG hibernateh2.HibernateEntityScanner - Discovered Hibernate-Entity class [edu.emory.cci.bindaas.core.model.hibernate.HistoryLog] in bundle [bindaas-core-impl]
15 Jan 2020 18:36:02,797 DEBUG hibernateh2.HibernateEntityScanner - Discovered Hibernate-Entity class [edu.emory.cci.bindaas.core.model.hibernate.UserRequest] in bundle [bindaas-core-impl]
15 Jan 2020 18:36:02,798 DEBUG hibernateh2.HibernateEntityScanner - Discovered Hibernate-Entity class [edu.emory.cci.bindaas.core.model.hibernate.VerifyEmail] in bundle [bindaas-core-impl]
15 Jan 2020 18:36:02,799 DEBUG hibernateh2.HibernateEntityScanner - Discovered Hibernate-Entity class [edu.emory.cci.bindaas.core.model.hibernate.BindaasEventInfo] in bundle [bindaas-core-impl]
Jan 15, 2020 6:36:03 PM org.hibernate.annotations.common.reflection.java.JavaReflectionManager <clinit>
INFO: HCANN000001: Hibernate Commons Annotations {5.1.0.Final}
Jan 15, 2020 6:36:03 PM org.hibernate.Version logVersion
INFO: HHH000412: Hibernate Core {4.3.11.Final}
Jan 15, 2020 6:36:03 PM org.hibernate.cfg.Environment <clinit>
INFO: HHH000206: hibernate.properties not found
Jan 15, 2020 6:36:03 PM org.hibernate.cfg.Environment buildBytecodeProvider
INFO: HHH000021: Bytecode provider name : javassist
Jan 15, 2020 6:36:03 PM org.hibernate.cfg.Configuration configure
INFO: HHH000043: Configuring from resource: /hibernate.cfg.xml
Jan 15, 2020 6:36:03 PM org.hibernate.cfg.Configuration getConfigurationInputStream
INFO: HHH000040: Configuration resource: /hibernate.cfg.xml
Jan 15, 2020 6:36:03 PM org.hibernate.cfg.Configuration doConfigure
INFO: HHH000041: Configured SessionFactory: null
Jan 15, 2020 6:36:03 PM org.hibernate.engine.jdbc.connections.internal.DriverManagerConnectionProviderImpl configure
WARN: HHH000402: Using Hibernate built-in connection pool (not for production use!)
Jan 15, 2020 6:36:03 PM org.hibernate.engine.jdbc.connections.internal.DriverManagerConnectionProviderImpl buildCreator
INFO: HHH000401: using driver [org.h2.Driver] at URL [jdbc:h2:bindaas]
Jan 15, 2020 6:36:03 PM org.hibernate.engine.jdbc.connections.internal.DriverManagerConnectionProviderImpl buildCreator
INFO: HHH000046: Connection properties: {user=sa, password=****}
Jan 15, 2020 6:36:03 PM org.hibernate.engine.jdbc.connections.internal.DriverManagerConnectionProviderImpl buildCreator
INFO: HHH000006: Autocommit mode: false
Jan 15, 2020 6:36:03 PM org.hibernate.engine.jdbc.connections.internal.DriverManagerConnectionProviderImpl configure
INFO: HHH000115: Hibernate connection pool size: 20 (min=1)
Jan 15, 2020 6:36:05 PM org.hibernate.dialect.Dialect <init>
INFO: HHH000400: Using dialect: org.hibernate.dialect.H2Dialect
Jan 15, 2020 6:36:06 PM org.hibernate.engine.transaction.internal.TransactionFactoryInitiator initiateService
INFO: HHH000399: Using default transaction strategy (direct JDBC transactions)
Jan 15, 2020 6:36:06 PM org.hibernate.hql.internal.ast.ASTQueryTranslatorFactory <init>
INFO: HHH000397: Using ASTQueryTranslatorFactory
Jan 15, 2020 6:36:06 PM org.hibernate.tool.hbm2ddl.SchemaUpdate execute
INFO: HHH000228: Running hbm2ddl schema update
Jan 15, 2020 6:36:06 PM org.hibernate.tool.hbm2ddl.SchemaUpdate execute
INFO: HHH000102: Fetching database metadata
Jan 15, 2020 6:36:06 PM org.hibernate.tool.hbm2ddl.SchemaUpdate execute
INFO: HHH000396: Updating schema
Jan 15, 2020 6:36:06 PM org.hibernate.tool.hbm2ddl.DatabaseMetadata getTableMetadata
INFO: HHH000262: Table not found: AuditMessage
Jan 15, 2020 6:36:06 PM org.hibernate.tool.hbm2ddl.DatabaseMetadata getTableMetadata
INFO: HHH000262: Table not found: BindaasEventInfo
Jan 15, 2020 6:36:06 PM org.hibernate.tool.hbm2ddl.DatabaseMetadata getTableMetadata
INFO: HHH000262: Table not found: HistoryLog
Jan 15, 2020 6:36:06 PM org.hibernate.tool.hbm2ddl.DatabaseMetadata getTableMetadata
INFO: HHH000262: Table not found: Policy
Jan 15, 2020 6:36:06 PM org.hibernate.tool.hbm2ddl.DatabaseMetadata getTableMetadata
INFO: HHH000262: Table not found: UserRequest
Jan 15, 2020 6:36:06 PM org.hibernate.tool.hbm2ddl.DatabaseMetadata getTableMetadata
INFO: HHH000262: Table not found: VerifyEmail
Jan 15, 2020 6:36:06 PM org.hibernate.tool.hbm2ddl.DatabaseMetadata getTableMetadata
INFO: HHH000262: Table not found: AuditMessage
Jan 15, 2020 6:36:06 PM org.hibernate.tool.hbm2ddl.DatabaseMetadata getTableMetadata
INFO: HHH000262: Table not found: BindaasEventInfo
Jan 15, 2020 6:36:06 PM org.hibernate.tool.hbm2ddl.DatabaseMetadata getTableMetadata
INFO: HHH000262: Table not found: HistoryLog
Jan 15, 2020 6:36:06 PM org.hibernate.tool.hbm2ddl.DatabaseMetadata getTableMetadata
INFO: HHH000262: Table not found: Policy
Jan 15, 2020 6:36:06 PM org.hibernate.tool.hbm2ddl.DatabaseMetadata getTableMetadata
INFO: HHH000262: Table not found: UserRequest
Jan 15, 2020 6:36:06 PM org.hibernate.tool.hbm2ddl.DatabaseMetadata getTableMetadata
INFO: HHH000262: Table not found: VerifyEmail
Jan 15, 2020 6:36:06 PM org.hibernate.tool.hbm2ddl.DatabaseMetadata getTableMetadata
INFO: HHH000262: Table not found: AuditMessage
Jan 15, 2020 6:36:06 PM org.hibernate.tool.hbm2ddl.DatabaseMetadata getTableMetadata
INFO: HHH000262: Table not found: BindaasEventInfo
Jan 15, 2020 6:36:06 PM org.hibernate.tool.hbm2ddl.DatabaseMetadata getTableMetadata
INFO: HHH000262: Table not found: HistoryLog
Jan 15, 2020 6:36:06 PM org.hibernate.tool.hbm2ddl.DatabaseMetadata getTableMetadata
INFO: HHH000262: Table not found: Policy
Jan 15, 2020 6:36:06 PM org.hibernate.tool.hbm2ddl.DatabaseMetadata getTableMetadata
INFO: HHH000262: Table not found: UserRequest
Jan 15, 2020 6:36:06 PM org.hibernate.tool.hbm2ddl.DatabaseMetadata getTableMetadata
INFO: HHH000262: Table not found: VerifyEmail
Jan 15, 2020 6:36:06 PM org.hibernate.tool.hbm2ddl.SchemaUpdate execute
INFO: HHH000232: Schema update complete
15 Jan 2020 18:36:07,076 DEBUG util.DynamicProperties - Loaded default properties. bindaas.authentication.properties (No such file or directory)
15 Jan 2020 18:36:07,108 DEBUG util.DynamicObject - Reading default properties for [bindaas.authorization]
15 Jan 2020 18:36:07,350 INFO  impl.FileSystemPersistenceDriverImpl - Metadata Store does not exist. Creating a new one
15 Jan 2020 18:36:07,945 INFO  impl.DefaultAPIKeyManager$ExpireKeysJob - Purged [0] expired API Keys from the database
Jan 15, 2020 6:36:09 PM org.apache.cxf.endpoint.ServerImpl initDestination
INFO: Setting the server's publish address to be http://0.0.0.0:9099/administration
SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
Jan 15, 2020 6:36:10 PM org.apache.cxf.endpoint.ServerImpl initDestination
INFO: Setting the server's publish address to be http://0.0.0.0:9099/info
Jan 15, 2020 6:36:10 PM org.apache.cxf.endpoint.ServerImpl initDestination
INFO: Setting the server's publish address to be http://0.0.0.0:9099/services
15 Jan 2020 18:36:10,359 INFO  bundle.BindaasInitializer - Middleware Started
15 Jan 2020 18:36:10,514 DEBUG util.DynamicObject - Reading default properties for [trusted-applications]
Jan 15, 2020 6:36:10 PM org.apache.cxf.endpoint.ServerImpl initDestination
INFO: Setting the server's publish address to be http://0.0.0.0:9099/trustedApplication
15 Jan 2020 18:36:10,576 DEBUG util.DynamicObject - Reading default properties for [bindaas-pseudo-sts]
Jan 15, 2020 6:36:10 PM org.apache.cxf.endpoint.ServerImpl initDestination
INFO: Setting the server's publish address to be http://0.0.0.0:9099/securityTokenService
15 Jan 2020 18:36:11,243 DEBUG util.DynamicObject - Reading default properties for [security-dashboard]
15 Jan 2020 18:36:11,661 DEBUG views.DashboardView - edu.emory.cci.bindaas.webconsole.servlet.views.DashboardView Initialized
15 Jan 2020 18:36:11,681 DEBUG views.AuditView - edu.emory.cci.bindaas.webconsole.servlet.views.AuditView Initialized
15 Jan 2020 18:36:11,935 DEBUG util.DynamicObject - Reading default properties for [bindaas.adminconsole]
15 Jan 2020 18:36:11,976 INFO  webconsole.WebConsoleStarter - WebConsole Started
15 Jan 2020 18:36:12,645 INFO  system.StartupEventPublisher - This Bindaas instance was built at: #Wed, 15 Jan 2020 18:34:43 -0500
15 Jan 2020 18:36:12,645 INFO  system.StartupEventPublisher - Bindaas Server started in [40.161] seconds

**Comment by pradeeban** [comment] 2020-01-16 00:19
If that doesn't help much, delete the binaries folder and rebuild it. Somehow one of your previous failed runs may have left a lock file in it. You should be able to just delete that lock file. But easier to just rebuild and re-run again.

Make sure to use Java 8 and Maven 3.

**Comment by Raj2367** [comment] 2020-01-17 19:34
@pradeeban 
my java version 
sibu@sibu-kumar: /bindaas$  java -version
openjdk version "1.8.0_232"
OpenJDK Runtime Environment (build 1.8.0_232-8u232-b09-0ubuntu1-18.04.1-b09)
OpenJDK 64-Bit Server VM (build 25.232-b09, mixed mode)

my maven version
sibu@sibu-kumar:~/bindaas$ mvn --version
Apache Maven 3.6.3 (cecedd343002696d0abb50b32b541b8a6ba2883f)
Maven home: /opt/apache-maven
Java version: 1.8.0_241, vendor: Oracle Corporation, runtime: /usr/lib/java/jdk1.8.0_241/jre
Default locale: en_IN, platform encoding: UTF-8
OS name: "linux", version: "4.15.0-74-generic", arch: "amd64", family: "unix"

I have deleted the previous binaries and 
1. Clone the master repo in new directory
2. cd bindaas
3. mvn clean install (it created a new folder in this directory named as "binaries")
4. cd binaries
5. tar xvzf bindaas-dist-4.0.1-202001180622-min.tar.gz ( your zip file is different from mine i.e. bindaas-dist-3.3.5-201806281144-min.tar.gz)
6. cd bin
7. sh startup.sh
8. then when I am trying to open  http://localhost:8080/dashboard/ it is showing the error mentioned above

**Comment by pradeeban** [comment] 2020-01-17 21:29
I am sorry I could not reproduce this error. Can you run and confirm whether at least one of the released versions (https://github.com/sharmalab/bindaas/releases) is working for you? That could give some hints.

Just to confirm: When you run Bindaas with that long command I mentioned before, did you get all the logs I got?

**Comment by Raj2367** [comment] 2020-01-17 22:19
I didn't get any logs when execute "sh startup.sh".
And when I execute "java -Dpid=BINDAAS_INSTANCE -Xmx1024m -jar org.eclipse.osgi_3.10.100.v20150529-1857.jar -console", it leads me to osgi console like this 
https://user-images.githubusercontent.com/41533712/72448299-c5dab900-37dc-11ea-9815-0c1c83305124.png
an d when I enter "ss" in that console it shows out put like https://github.com/sharmalab/bindaas/issues/98#issuecomment-574722095

**Comment by Raj2367** [comment] 2020-01-18 19:54
@pradeeban Binary with version 3.4.7 working properly for me...finally :)


![Screenshot from 2020-01-19 06-48-44](https://user-images.githubusercontent.com/41533712/72669625-4823e100-3a5a-11ea-9f74-840be1119be8.png)

**Comment by pradeeban** [comment] 2020-01-21 14:48
There is a whole bunch of logs missing in your screenshot and that's worrying.

At least Bindaas 3.4.8 works. Can you retry with the Bindaas latest release (v 4.0.0)?

**Comment by pradeeban** [comment] 2020-01-24 17:35
Closing, as this is mostly a personal issue in building the project. Feel free to comment if you have updates.

**Closed by pradeeban** 2020-01-24 17:35 UTC
Labels: help wanted
