### ISSUE TITLE
User/Key Deletion doesn't seem to work concistently

### ISSUE THREAD

**Issue by birm** [sharmalab/bindaas#12] opened 2018-05-11 19:52 UTC
Creating a user then deleting it makes it disappear from the user list, but the key still works, at least for some time. This suggests that at least one of list or delete is wrong.

PROCEDURE: (from camicroscope signup application)

> bash add_user.sh test3 test3 10/10/2020
> java -jar trusted-app-client-0.0.1-jar-with-dependencies.jar -action i -username test3 -id camicSignup -secret 9002eaf56-90a5-4257-8665-6341a5f77107 -comments loader -lifetime 999  -url http://quip-data:9099/trustedApplication
> bash list_user.sh
> #[{"value":"c10179b6-030b-4461-8395-88b7d6c1d560","expires":"Jan 1, 2050 12:00:00 AM","applicationName":"caMic Signup App","applicationID":"camicSignup","username":"loader@quip"},{"value":"2dcb75bf-e773-451f-8541-f7fd25a1b6e4","expires":"Jan 1, 2050 12:00:00 AM","applicationName":"caMic Signup App","applicationID":"camicSignup","username":"viewer@quip"},{"value":"cc73b4cc-cb47-4bf8-bfb7-025ebcc12c8d","expires":"Oct 10, 2020 12:00:00 AM","applicationName":"caMic Signup App","applicationID":"camicSignup","username":"test3@localhost"},{"value":"f560ca22-6c17-4f53-a930-e486e5928705","expires":"May 11, 2018 8:04:21 PM","applicationName":"caMic Signup App","applicationID":"camicSignup","username":"test3@localhost"}]
> curl -v quip-data:9099/services/caMicroscope_Templates/AnnotationTemplate/query/retrieveTemplate?api_key=f560ca22-6c17-4f53-a930-e486e5928705
> curl -v quip-data:9099/services/caMicroscope_Templates/AnnotationTemplate/query/retrieveTemplate?api_key=cc73b4cc-cb47-4bf8-bfb7-025ebcc12c8d
> #(both above work)
> bash delete_user.sh test3
> bash list_user.sh
> #[{"value":"c10179b6-030b-4461-8395-88b7d6c1d560","expires":"Jan 1, 2050 12:00:00 AM","applicationName":"caMic Signup App","applicationID":"camicSignup","username":"loader@quip"},{"value":"2dcb75bf-e773-451f-8541-f7fd25a1b6e4","expires":"Jan 1, 2050 12:00:00 AM","applicationName":"caMic Signup App","applicationID":"camicSignup","username":"viewer@quip"}]
> curl -v quip-data:9099/services/caMicroscope_Templates/AnnotationTemplate/query/retrieveTemplate?api_key=f560ca22-6c17-4f53-a930-e486e5928705
> curl -v quip-data:9099/services/caMicroscope_Templates/AnnotationTemplate/query/retrieveTemplate?api_key=cc73b4cc-cb47-4bf8-bfb7-025ebcc12c8d
> #(both above still work)

**Comment by pradeeban** [comment] 2018-07-09 15:23
Relevant files for the context of this issue - https://github.com/camicroscope/Security/tree/master/Admin

**Comment by pradeeban** [comment] 2018-07-10 19:02
More precisely, the original project is at https://github.com/nadirsaghar/Bindaas-Trusted-App-Client-API

**Comment by pradeeban** [comment] 2018-07-10 20:10
As far as the client is concerned, the user/key deletion works.

My steps:

Checkout the java client project - https://github.com/nadirsaghar/Bindaas-Trusted-App-Client-API

Go to the class TestTrustedAppClient.

Then go to the method: testAuthorizeNewUser()
Change the line 23 as below:
//		Long epochTimeExpires = (new Date()).getTime() + 1000*600; // expires in 10 min


This change makes your expiration time to 10 minutes, from the current 1 min (since 1 minute may be too quick for you to test this to be working),

Now, execute only testAuthorizeNewUser() method.

After an execution, use the testListAPIKey() method. The output will be as below:

`Digest of (demo-id,demo-secret-key,b28631c2-a3f0-49cf-b247-643663566532,6b02a0a2-afad-48a2-926c-9a619db36714,15312501)=6q8nDcu+qr1ERxXiZeWoy2qogYE=
[{"value":"0cf4c3c6-c640-4a5f-8da0-eb7dc8661f55","expires":"Jul 10, 2058 2:25:36 PM","applicationName":"Demo Application","applicationID":"demo-id","username":"admin@localhost"}, {"value":"b6d329cf-2ff2-4fb6-92bb-b53a5e062bf9","expires":"Dec 31, 2060 12:00:00 AM","applicationName":"Demo Application","applicationID":"demo-id","username":"test-user-1@localhost"}, {"value":"ea6dbfef-56ab-4e88-9420-69386d128855","expires":"Jul 10, 2018 3:21:29 PM","applicationName":"Demo Application","applicationID":"demo-id","username":"2ee025b6-0043-4c3b-ac10-32f1883c0391@localhost"}]
3`

Now, modify the testRevokeAccess() as below
`	@Test
	public void testRevokeAccess()
	{
		String url = "http://localhost:9099/trustedApplication";
		String applicationID = "demo-id";
		String applicationSecret = "demo-secret-key";
		String randomUser = "ea6dbfef-56ab-4e88-9420-69386d128855";
//		Long epochTimeExpires = (new Date()).getTime() + 1000*60; // expires in 1 min
		String comments = "junit testing";
		TrustedAppClientImpl client = new TrustedAppClientImpl(url,applicationID, applicationSecret);
		try {
//			APIKey masterKey = client.authorizeNewUser(randomUser, epochTimeExpires, comments);
//			Assert.assertNotNull(masterKey);
//			System.out.println(masterKey);
			String resp = client.revokeAccess(randomUser, comments);
			Assert.assertNotNull(resp);
			System.out.println(resp);
		} catch (Exception e) {
			e.printStackTrace();
			Assert.fail(e.getMessage());

		}
	}`

Make sure to replace the value of the `randomUser` with the value of the newly created user that you would like to delete (find it from the previous create logs as in the below:)
`{"value":"ea6dbfef-56ab-4e88-9420-69386d128855","expires":"Jul 10, 2018 3:21:29 PM","applicationName":"Demo Application","applicationID":"demo-id","username":"2ee025b6-0043-4c3b-ac10-32f1883c0391@localhost"}]
3`
		String randomUser = "2ee025b6-0043-4c3b-ac10-32f1883c0391";


Now, execute the testRevokeAccess().

Then execute the list testListAPIKey().




Before the deletion:
`Digest of (demo-id,demo-secret-key,b28631c2-a3f0-49cf-b247-643663566532,6b02a0a2-afad-48a2-926c-9a619db36714,15312501)=6q8nDcu+qr1ERxXiZeWoy2qogYE=
[{"value":"0cf4c3c6-c640-4a5f-8da0-eb7dc8661f55","expires":"Jul 10, 2058 2:25:36 PM","applicationName":"Demo Application","applicationID":"demo-id","username":"admin@localhost"}, {"value":"b6d329cf-2ff2-4fb6-92bb-b53a5e062bf9","expires":"Dec 31, 2060 12:00:00 AM","applicationName":"Demo Application","applicationID":"demo-id","username":"test-user-1@localhost"}, {"value":"ea6dbfef-56ab-4e88-9420-69386d128855","expires":"Jul 10, 2018 3:21:29 PM","applicationName":"Demo Application","applicationID":"demo-id","username":"2ee025b6-0043-4c3b-ac10-32f1883c0391@localhost"}]
3`


After the deletion:
`Digest of (demo-id,demo-secret-key,c2de02e6-5dda-4351-adce-2f383719e49f,c6dc1694-3926-4511-97cc-50fb75575eb5,15312502)=G3pEGa0Y1rizjNntGOf7pK1yBTs=
[{"value":"0cf4c3c6-c640-4a5f-8da0-eb7dc8661f55","expires":"Jul 10, 2058 2:25:36 PM","applicationName":"Demo Application","applicationID":"demo-id","username":"admin@localhost"}, {"value":"b6d329cf-2ff2-4fb6-92bb-b53a5e062bf9","expires":"Dec 31, 2060 12:00:00 AM","applicationName":"Demo Application","applicationID":"demo-id","username":"test-user-1@localhost"}]
2
`

**Comment by pradeeban** [comment] 2018-07-10 20:12
or revoke access using the command line:

$ java -jar trusted-app-client-0.0.1-jar-with-dependencies.jar -action r -username b9f5bbda-46e1-4517-a331-b096b6f78852 -id demo-id -secret demo-secret-key  -comments 'Removing new Account' -url http://localhost:9099/trustedApplication
Digest of (demo-id,demo-secret-key,7094ed80-6df3-479d-92ef-904678a0c232,b9f5bbda-46e1-4517-a331-b096b6f78852,15312532)=mPhRJbeYrRV3HZ3UB1eHRK7mCLY=
Server Returned :
{"username":"b9f5bbda-46e1-4517-a331-b096b6f78852","keys_deleted":1,"applicationID":"demo-id","applicationName":"Demo Application"}

**Comment by pradeeban** [comment] 2018-07-11 18:05
In the master, the current max time limit is set to 3 hours. I was able to reproduce this issue.

**Comment by pradeeban** [comment] 2018-07-11 19:05
I have narrowed down the issue. The issue is more sinister with short-lived api keys than we thought. Regardless of whether you delete the user, revoke the access to the key through the admin dashboard, or whether the key expired on its own, it continues to work until you restart Bindaas.

**Comment by pradeeban** [comment] 2018-07-11 19:10
It took me some time to understand the issue. But with the help of @birm, I managed to reproduce this.

A short-lived API key can become invalid for the below reasons:
1. You delete the user.
2. The API key reaches the expiration time.
3. You revoke the access of the key (through the management console).

Once one of these 3 actions happens, the key is removed from the lists. However, until you restart Bindaas, the key actually works. Once you have restarted Bindaas, it stops working.

This issue is only with the short-lived API keys. 
I have made a hard-limit of 3 hours for the API keys (so that you cannot set a lifetime of infinity to the keys) in the master. However, with this new findings, the positive impact of that fix is marginal (as they keys will continue to work until you restart Bindaas after one of those 3 events).

**Comment by pradeeban** [comment] 2018-07-11 20:44
There is a constant that defines how long the authentication and authorization are cached. Currently, it is set to 60 minutes. I am resetting it to 1 minute and re-testing.
`private static final Long DECISION_CACHE_TIMEOUT_MINUTES`

**Comment by nadirsaghar** [comment] 2018-07-11 21:01
consider moving to OAuth 2.0 and more specifically to JWT(JSON Web Token) for the purposes of authorization.
JWT are much more scalable and secure alternative to the short lived API keys generated within Bindaas.

**Comment by pradeeban** [comment] 2018-07-11 21:09
So it is a feature. :P 

It gives you stickiness, rolling.

16:55:44 - Access a service with a new key for the first time. It authenticates.
16:56:24 - Second access. No authentication, since it is within 1 minute from the previous access.
16:56:53 - Third access. No authentication, since it is within 1 minute from the previous access.
16:57:30 - Delete the user, and access again. Still works, since it is still within 1 minute time frame.
16:57:50 - Still works without authentication.
16:58:14 - Still works.
17:01:55 - Does not work anymore, since the previous access happened more than 1 minute ago, and since the cache was invalidated.

**Comment by pradeeban** [comment] 2018-07-11 21:11
@nadirsaghar   Thanks for your feedback.

Can you recall whether there is a valid reason for caching the authentication in Bindaas? Currently, it works well when I set it to 1 minute instead of 60 minutes. But can I set it to 0? Please let me know if there is any implication.

**Comment by nadirsaghar** [comment] 2018-07-11 22:39
@pradeeban your guess is correct. It was done for performance reasons. The api_key is validated against the database. You don't want to making a database call each time an API request comes through. Instead of reducing the caching time, I'd suggest invalidating the cache whenever an api_key is revoked. At the end of the day, it's not going to hamper performance even if you reduce the caching duration since Bindaas is backed by HSQL, backed by local file system. In a production environment and/or clustered environment, I'd imagine something like MySQL or MongoDB might be used. In that case caching benefits would certainly be realized

**Comment by pradeeban** [comment] 2018-07-12 00:36
@nadirsaghar Thanks a lot for your pointers. H2 is very efficient. But I understand your concerns when another backend such as MongoDB is used. I will look into this again soon.

**Closed** 2018-07-13 17:48 UTC

**Comment by tushar-97** [comment] 2019-06-11 20:52
There is still an issue if we refresh the key from the admin console. Steps to reproduce it:
1. Login to get api_key (say k1)
2. All APIs will use k1
3. Now refresh the key to get k2
4. The APIs of the data providers still use k1 for making the requests. k2 also works (if you change the key in the url) but is not picked up by default

I am almost certain that k1 still works because it's cached and we do not invalidate it when we refresh the key (modifyAPIKey method in DefaultApiKeyManager).
